export const PRESUPUESTO_INICIAL_H2_TEXT = "Introduce Presupuesto";
export const PRESUPUESTO_PLACEHOLDER = "Presupuesto";
export const SUBMIT_BUTTON_TEXT = "Guardar"; 
export const PRESUPUESTO_INICIAL_ERROR_MESSAGE = "Presupuesto NO VÁLIDO. Asegúrese de que sea mayor a 1 o que no esté el campo vacío";
export const ERROR_DATOS_INCORRECTO_INCOMPLETO = "Datos incorrectos o incompletos";
export const ERROR_SIN_PRESUPUESTO = "Presupuesto Acabado"
export const FORMULARIO_GASTOS_H2_TEXT = "Gasto nuevo";
export const FORMULARIO_GASTOS_CANTIDAD_TEXT = "Ej: 20";
export const FORMULARIO_GASTOS_GASTO_LABEL_TEXT = "Cantidad";
export const FORMULARIO_GASTOS_CONCEPTO_TEXT = "En qué se gastó?";
export const FORMULARIO_GASTOS_CONCEPTO_LABEL_TEXT = "Concepto";
export const FORMULARIO_GASTOS_SUBMIT_BUTTON_TEXT = "Guardar";
export const FORMULARIO_GASTOS_ERROR_MESSAGE = "Necesitas completar ambos campos";
export const LISTADO_GASTOS_H2_TEXT = "Gastos Realizados";
export const PRESUPUESTO_DASHBOARD_INFORMACION_H2 = "Información";
export const PRESUPUESTO_DASHBOARD_PRESUPUESTO_P = "Presupuesto inicial: €";
export const PRESUPUESTO_DASHBOARD_DISPONIBLE_P = "Disponible actual: €";
export const RESTANTE_HELPER_CLASE_SUCCESS = "alert alert-success";
export const RESTANTE_HELPER_CLASE_WARNING = "alert alert-warning";
export const RESTANTE_HELPER_CLASE_DANGER = "alert alert-danger";
export const RESTANTE_ERROR_MESSAGE = "Vaya... te has quedado sin dinero... añade más dinero al presupuesto o no gastes más!"